name: CI

on:
  push:
    branches: [ master, v4 ]
  pull_request:
    branches: [ master, v4 ]

env:
  DEVELOPER_DIR: /Applications/Xcode_11.6_beta.app
  
jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild clean build -project CovidWatch.xcodeproj -scheme CovidWatch-Arizona-Dev -destination "platform=iOS Simulator,name=iPhone 11 Pro Max"
